### PR TITLE
Manual UI Creation Bug Fix (soome pages not rendering)

### PR DESCRIPTION
**Pull request by bbearce**
# Issue description
Some pages aren't showing if you are not in a phase.

# Issues this PR resolves
- #1180

# A checklist for hand testing
- [x] Upload competition
- [x] Delete all but one phase
- [x] Make sure you can access all html pages
- [x] Repeat for pre-existing and manually created challenges

# Any relevant files for testing
[iris_competition_bundle_vetted.zip](https://github.com/codalab/codabench/files/14358178/iris_competition_bundle_vetted.zip)

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [x] Code review by reviewer
- [x] Hand tested by reviewer
- [x] CircleCi tests are passing
- [x] Ready to merge

### CODE REVIEW

**Comment by ihsaan-ullah** [comment]
What was the actual problem?

**Comment by bbearce** [comment]
So elusive man. Phases have these two types of statuses. status and is_final_phase. Generally speaking if the phase status is current then everything works out fine. In our case is there is no current phase and there is some JavaScript trying to look up in that case if the is_final_phase of any phase in this challenge is the final phase. That part wasn't working because even if you only have one phase there was no guarantee it was the final. To me it was a back end bug where if a challenge only has one phase it needs to always say that it is the final phase in the data base. It wasn't doing that and it was getting kind of tricky for me to figure out. So instead of hacking the front end to just figure out if there's only one phase and force the issue, I decided to change the back end to adjust the phase's attribute appropriately.

**Comment by Didayolo** [comment]
@bbearce By default `is_final_phase` is False? Where is it defined?

**Comment by ihsaan-ullah** [comment]
I think this 'is_final_phase' is not needed. We can remove it from the model and remove this logic. But maybe in another PR. The db design is not what i would do in this case

**Pull request merged**
