### PR TITLE
Compute worker - docker pull image + execution time limit crash

### PR DESCRIPTION
**Pull request by ihsaan-ullah**
# @ mention of reviewers
@Didayolo 

# A brief description of the purpose of the changes contained in this PR.
Now users can see the following error logs:
1. docker image pull failure logs in ingestion std_err
2. execution time limit logs in ingestion or scoring std_err

# Screenshots

**Docker image pull**
Screenshot 2023-09-17 at 8 28 05 PM

Screenshot 2023-09-17 at 8 28 16 PM

**Execution time limit Ingestion**
Screenshot 2023-09-18 at 1 14 38 AM
Screenshot 2023-09-18 at 1 14 54 AM

**Execution time limit Scoring**
Screenshot 2023-09-18 at 1 31 26 AM
Screenshot 2023-09-18 at 1 31 39 AM

# Issues this PR resolves
- #902 

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [x] Code review by reviewer
- [x] Hand tested by reviewer
- [x] CircleCi tests are passing
- [x] Ready to merge

### CODE REVIEW

**Comment by Didayolo** [comment]
That is awesome!

In case of another problem (not docker pull or time limit), is the error log transmitted too?

**Comment by ihsaan-ullah** [comment]
> That is awesome!
> 
> In case of another problem (not docker pull or time limit), is the error log transmitted too?

I cannot think of any other problem which may occur outside the running of the submission. Docker pull is happening before running the submission and execution time limit is also outside the submission execution. But if there is any other scenario, I can check that

**Comment by Didayolo** [comment]
I think that was the main scenarios indeed. Others scenarios are basically bugs inside the code of the compute worker. For instance de BadZipFile that we have fixed already. We can just assume there is no other bug while nothing is reported.

**Comment by ihsaan-ullah** [comment]
> I think that was the main scenarios indeed. Others scenarios are basically bugs inside the code of the compute worker. For instance de BadZipFile that we have fixed already. We can just assume there is no other bug while nothing is reported.

Yes, I agree. Now I think if there is any other bug, it can be fixed in less time as now things seems to be working

**Comment by Didayolo** [comment]
I suggest to test this PR in this way:

- [ ] Push the compute worker docker to `codalab/competitions-v2-compute-worker:test` (note the `test` tag).
- [ ] By the way, we can remove the image with tag `retries` from DockerHub.
- [ ] Update the compute workers of the default queue of https://codabench-test.lri.fr/ with this new docker image.
- [ ] Try different submission on codabench-test, exceeding execution time limit or not, etc.

This procedure can be used for future developments too.

**Comment by ihsaan-ullah** [comment]
> * [ ]  Push the compute worker docker to `codalab/competitions-v2-compute-worker:test` (note the `test` 

why the comute worker docker image.

**Comment by Didayolo** [comment]
> why the compute worker docker image.

To reflect changes done on `compute_worker.py`, we need to build the docker image and push it to dockerhub.

**Pull request merged**
