### PR TITLE
File size added in readable format in Resources -> Datasets

### PR DESCRIPTION
**Pull request by ihsaan-ullah**
# @ mention of reviewers
@Didayolo 

# A brief description of the purpose of the changes contained in this PR.
Now users can see file size in readable format in Resources -> Datasets
Screenshot 2023-05-26 at 2 44 26 PM

# Issues this PR resolves
#713 -> Interfaces -> Point 1

> Add the size of the files

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [x] Code review by reviewer
- [x] Hand tested by reviewer
- [x] CircleCi tests are passing
- [x] Ready to merge

### CODE REVIEW

**Comment by Didayolo** [comment]
Thank you for the PR.

I think it breaks the buttons to navigate through pages in the resources interface (bottom right):

Capture d’écran 2023-05-26 à 15 38 43

**Comment by Didayolo** [comment]
Nice work!

**Comment by ihsaan-ullah** [comment]
@Didayolo 

When a submissions file is stored, the standard used for Kilobytes (KB) is 1024 and not 1000.
https://github.com/codalab/codabench/blob/develop/src/apps/datasets/models.py#L67

In the change I have made, I use 1000.
```python
// loop over n until it is greater than 1000
while(n >= 1000 && ++i){
     n = n/1000;
 }
```

Should this be changed to 1024?

**Comment by Didayolo** [comment]
So I guess right now we showing MiB, GiB, etc. instead of MB or GB.

Yes, maybe it is better to change this to 1024.

**Comment by ihsaan-ullah** [comment]
I think KiB, MiB,  GiB are multiples of 1024 while KB, MB, GB are multiples of 1000.

my change is showing KB, MB, Gb.

**Comment by Didayolo** [comment]
OK then we can let it as it is, because the information provided is accurate.

**Pull request merged**
