### PR TITLE
Download buttons

### PR DESCRIPTION
**Pull request by bbearce**
# @ mention of reviewers
@Didayolo 
@ihsaan-ullah 

# A brief description of the purpose of the changes contained in this PR.
Adding the ability to add/edit public_data and starting_kit in phase.

Status:
- [x] Starting Kit and Public Data need to be phase level objects. - DONE
- [x] Need to see in Files list. - DONE
- [x] Need to add phase edit ability to see datasets as options to be selected and associated to phase. - DONE
- [x] Need to save to database on competition edit save. - DONE
- [x] Then need to adjust unpacker to allow them through via yaml for both v1 and v2. - DONE
- [FOR NEXT PR] Need to be able to decide what datasets are public. - NOT DONE
DISCLAIMER NOT DONE --> separated PR

# Issues this PR resolves
- #277
- #723
- #764

# A checklist for hand testing  
## Make competition upload bundle  
- [x] Upload a **V1** bundle with starting kit and public data and check it's there
- [ ] Upload a **V2** bundle with starting kit and public data **as ZIP files** and check it's there
- [ ] Upload a **V2** bundle with starting kit and public data **as folders** and check it's there
- [x] Add Phase with public_data and starting_kit with at least one task with other 4 datasets (id, rf, ip, sp)  
- [x] Add Phase with no public_data or starting_kit with at least one task with other 4 datasets (id, rf, ip, sp)  
- [ ] Add Phase with public_data only with at least one task with other 4 datasets (id, rf, ip, sp)  
- [ ] Add Phase with starting_kit only with at least one task with other 4 datasets (id, rf, ip, sp)  
- [ ] Try with more than one phase as well with at least one task with other 4 datasets (id, rf, ip, sp) with both tasks with other 4 datasets (id, rf, ip, sp)  
- [ ] Check competition has data you expect in Files list under Get Started and in Competition editor under phases  

## Make manual competition  
- [ ] * Add Phase with public_data and starting_kit with at least one task with other 4 datasets (id, rf, ip, sp)  
- [ ] * Add Phase with no public_data or starting_kit with at least one task with other 4 datasets (id, rf, ip, sp)  
- [ ] * Add Phase with public_data only with at least one task with other 4 datasets (id, rf, ip, sp)  
- [ ] * Add Phase with starting_kit only with at least one task with other 4 datasets (id, rf, ip, sp)  
- [ ] Try with more than one phase as well with at least one task with other 4 datasets (id, rf, ip, sp) with both tasks with  other 4 datasets (id, rf, ip, sp)  
- [ ] Save and check competition has data you expect in Files list under Get Started and in Competition editor under phases  

## Edit pre-existing competition  
- [x] * Edit Phase with public_data and starting_kit and change both to none  
- [x] * Edit Phase with no public_data or starting_kit and change both to something  
- [x] * Edit Phase with public_data only and make starting_kit only  
- [x] * Edit Phase with starting_kit only and make public_data only  
- [ ] Try with more than one phase as well  
- [ ] Save and check competition has data you expect in Files list under Get Started and in Competition editor under phases  

## Double Check
- [x] In Competition go under Get Started \ Files and check that the files visible match the files in:  
- [x] * All datasets attached to each task  
- [x] * public_data and or starting_kit associated with each phase  

# Any relevant files for testing
...I can make a variation on classify wheat seeds for this testing

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [x] Code review by reviewer
- [x] Hand tested by reviewer
- [x] CircleCi tests are passing
- [x] Ready to merge

### CODE REVIEW

**Comment by bbearce** [comment]
# comments 
* red stars by public_data and starting_kit don't need to be there.
* allow multiple public_data and starting_kits

**Comment by Didayolo** [comment]
- Before the second PR, scoring program, ingestion program and input data should be **unavailable** by default (we do not want to force it to be public)
- If there is no public data, starting kit, and everything else is not available, there should be a default sentence inside the table, like for the leaderboard:

Capture d’écran 2023-07-18 à 17 27 20

**Comment by Didayolo** [comment]
Hi @bbearce, I am testing this PR.

I can see the download buttons for starting kit and public data even if I am not logged in the platform nor registered for the competition.

As a reminder:

> - For non-approved participants: Not accessible
> - For approved participants: Showing objects made available by organizers

**Comment by bbearce** [comment]
Let me take a look.

**Comment by bbearce** [comment]
Ok here are the fixes:
* For non-approved participants: Not accessible:  
image

* For approved participants: Showing objects made available by organizers:  
Organizers can unselect starting_kit and public_data and it won't be available.

**Comment by Didayolo** [comment]
@bbearce That is great! Thank you for the detailed screenshots. I'll review it as soon as possible.

**Comment by Didayolo** [comment]
It is working fine. However, I see this in the logs, which seems to be related to the changes:

```python
codabench-site_worker-1  | Traceback (most recent call last):
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 382, in trace_task
codabench-site_worker-1  |     R = retval = fun(*args, **kwargs)
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 641, in __protected_call__
codabench-site_worker-1  |     return self.run(*args, **kwargs)
codabench-site_worker-1  |   File "/app/src/apps/competitions/tasks.py", line 754, in submission_status_cleanup
codabench-site_worker-1  |     for sub in submissions:
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 274, in __iter__
codabench-site_worker-1  |     self._fetch_all()
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1242, in _fetch_all
codabench-site_worker-1  |     self._result_cache = list(self._iterable_class(self))
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 55, in __iter__
codabench-site_worker-1  |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
codabench-site_worker-1  |     cursor.execute(sql, params)
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
codabench-site_worker-1  |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
codabench-site_worker-1  |     return executor(sql, params, many, context)
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
codabench-site_worker-1  |     return self.cursor.execute(sql, params)
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
codabench-site_worker-1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
codabench-site_worker-1  |     return self.cursor.execute(sql, params)
codabench-site_worker-1  | django.db.utils.ProgrammingError: column competitions_phase.public_data_id does not exist
codabench-site_worker-1  | LINE 1: ...r_person", "competitions_phase"."leaderboard_id", "competiti...
```

**Comment by Didayolo** [comment]
What is the YAML syntax for starting kit and public data? We need to update the documentation

**Comment by Didayolo** [comment]
All files are shown as available:

Capture d’écran 2023-07-25 à 11 38 47

I'll merge anyway so we can start testing the feature on codabench-test, but this needs to be addressed.

**Comment by Didayolo** [comment]
I added the remaining TODOs in #764 ("second PR")

**Comment by Didayolo** [comment]
Solutions are available even if not logged in, and the table shows "No Files Available Yet"

Capture d’écran 2023-07-25 à 12 32 10

**Comment by bbearce** [comment]
Bah! Ok. Working on the Solution and No Files Yet issue.

**Pull request merged**
