### PR TITLE
Show competition name and file name in Resources -> Datasets

### PR DESCRIPTION
**Pull request by ihsaan-ullah**
# @ mention of reviewers
@Didayolo 

# A brief description of the purpose of the changes contained in this PR.
Now users can see :

- [x] Actual file name if available  in the table
- [x] Competition name to which this submissions belongs
- [x] Actual file name in the dataset detail title
- [x] Competition name is a clickable link to the competition page 

In Resources -> Datasets
Screenshot 2023-05-27 at 6 31 52 PM

In Resources -> Datasets -> Detail
Screenshot 2023-05-27 at 4 07 54 PM

Note for old submissions:
1. Competition name will be empty
2. File name will be dataset name instead of new actual file name for both table and dataset detail title

# Issues this PR resolves
#713 -> Interface -> Point 2,3,4

> Submission details: in which benchmark
> make benchmark name clickable link
> Submission: name it using the filename

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [x] Code review by reviewer
- [x] Hand tested by reviewer
- [x] CircleCi tests are passing
- [x] Ready to merge

### CODE REVIEW

**Comment by Didayolo** [comment]
Very nice change!

I guess, as for the job status page (#744), it would be even better if benchmark names were clickable links that open the benchmark in a new tab.

I'll test this asap.

**Comment by ihsaan-ullah** [comment]
@Didayolo now it should be ok

**Comment by Didayolo** [comment]
@ihsaan-ullah Oh I was pushing the same change right now!

**Comment by Didayolo** [comment]
So I'll discard my change and pull yours (it is the same anyway).

**Comment by Didayolo** [comment]
Some problem with this:

- The name given when uploading a dataset is not shown anymore:
Capture d’écran 2023-05-27 à 15 50 42

- When a dataset or a program is in use in a competition task, we see the tag "In use" but "Competition In" is empty:

Capture d’écran 2023-05-27 à 15 52 19


I think this is related to the need to separate the submissions and the datasets (data and programs) in different tabs. Because this change is great for submissions but not for datasets.

**Comment by ihsaan-ullah** [comment]
Yes, these conflicts will be solved when datasets and submissions are separated. We are in good direction

**Pull request merged**
