### PR TITLE
Separate Tab for submissions in Resources

### PR DESCRIPTION
**Pull request by ihsaan-ullah**
# @ mention of reviewers
@Didayolo 

# A brief description of the purpose of the changes contained in this PR.
Main goal of this PR is to add separate tab for submissions and some small additional stuff

- [x] Added separate tab for submissions
Screenshot 2023-05-28 at 3 09 41 PM

- [x] Submissions removed from Datasets and programs tab
Screenshot 2023-05-28 at 3 10 05 PM

- [x] Competition in removed from Datasets and programs
- [x] Title entered used in Datasets and programs
- [x] Actual file name used only in submissions tab
- [x] Filter for type removed from Submissions tab
- [x] Add Dataset/Program -> Type submission removed from dropdown list of types
- [x] Add/upload new submission modal added
- [x] Dataset detail: Benchmark id changed to benchmark name 
- [x] Tasks tab: Benchmark names are now clickable links

# Issues this PR resolves
#713 -> Interface -> Point 6

> Have a separate tab for submissions

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [x] Code review by reviewer
- [x] Hand tested by reviewer
- [x] CircleCi tests are passing
- [x] Ready to merge

### CODE REVIEW

**Comment by Didayolo** [comment]
Very nice PR, that was efficient. I'll test it in depth as there are many changes.

**Comment by Didayolo** [comment]
This was already like this, but the benchmarks could be clickable URL in the "Task" tab too:

Capture d’écran 2023-05-30 à 13 22 55

**Comment by ihsaan-ullah** [comment]
Used by Benchmark id is now fixed:
Screenshot 2023-05-30 at 5 03 38 PM

Benchmark as a link in tasks needs more investigation

**Comment by ihsaan-ullah** [comment]
Screenshot 2023-05-30 at 5 50 26 PM

Benchmarks in tasks table is now a clickable link

**Pull request merged**
