### PR TITLE
CPU limit on default queue

### PR DESCRIPTION
**Pull request by bbearce**
# Limit CPU usage on the default queue
@Didayolo 

# A brief description of the purpose of the changes contained in this PR.
**Limit duration of submissions** (DONE): We should add an option in the .env file specifying a maximum execution time limit for jobs in the default queue (main queue of the platform).

**Limit submissions** (DONE): This way, the main queue could not get blocked by long jobs running in parallel. This would incentivize organizers to use their own queue if they want to make more ambitious benchmarks.

# Issues this PR resolves
- #1141

# A checklist for hand testing
- [x] create a queue and get it working and attached to competition (attached below) or custom comp you already have.

- [x] default queue:
  * MAX_EXECUTION_TIME_LIMIT=20 in .env file; 
  * time.sleep(15) in score.py in attached competition or other comp; 
  * set phase execution_time_limit to 10 seconds
  * submission should **fail** as 15 seconds is longer than 10 sec limit and below default queue limit

- [x] default queue:
  * MAX_EXECUTION_TIME_LIMIT=20 in .env file; 
  * time.sleep(15) in score.py in attached competition or other comp; 
  * set phase execution_time_limit to 35 seconds
  * submission should **pass** as 15 seconds is less than 35 sec limit and below default queue limit

- [x] default queue:
  * MAX_EXECUTION_TIME_LIMIT=20 in .env file; 
  * time.sleep(25) in score.py in attached competition or other comp; 
  * set phase execution_time_limit to 35 seconds
  * submission should **fail** as 25 seconds is longer than 20 sec default queue limit regardless of execution_time_imit

- [x] custom queue:
  * MAX_EXECUTION_TIME_LIMIT=20 in .env file; 
  * time.sleep(15) in score.py in attached competition or other comp; 
  * set phase execution_time_limit to 10 seconds
  * submission should **fail** as 15 seconds is longer than 10 sec execution_time_imit

- [x] custom queue:
  * MAX_EXECUTION_TIME_LIMIT=20 in .env file; 
  * time.sleep(15) in score.py in attached competition or other comp; 
  * set phase execution_time_limit to 35 seconds
  * submission should **pass** as 15 seconds is less than 35 sec execution_time_imit

- [x] custom queue:
  * MAX_EXECUTION_TIME_LIMIT=20 in .env file; 
  * time.sleep(25) in score.py in attached competition or other comp; 
  * set phase execution_time_limit to 35 seconds
  * submission should **pass** as 25 seconds is less than 35 sec execution_time_imit

# Any relevant files for testing
[template_v2_competition_bundle.zip](https://github.com/codalab/codabench/files/12582071/template_v2_competition_bundle.zip)

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [x] Code review by reviewer
- [x] Hand tested by reviewer
- [x] CircleCi tests are passing
- [x] Ready to merge

### CODE REVIEW

**Comment by Didayolo** [comment]
If I understand, it is here that you ignore the platform time limit if we are not using the default queue?

```python
[tasks.py]
    if submission.phase.competition.queue:
        submission.queue_name = submission.phase.competition.queue.name or ''
        run_args['execution_time_limit'] = submission.phase.execution_time_limit
        submission.save()
```

I think some comments should be added to clarify this.

Also, here, `600` is hard-coded and not read from the environment variable, so it may be wrong:

```
[_phases.tag]
Execution Time Limit (seconds)<span data-tooltip="600s if unset, 600s max with default queue."
```

**Comment by Didayolo** [comment]
> If you meant the below code or the UI, yes right now it is always 600 to begin with unless you edit it

Yes, I meant that the UI is not aligned with the actual value of the parameter.

**Comment by ihsaan-ullah** [comment]
This is a guide which shows how to use redis with python
https://redis.io/docs/clients/python/

I think it should be discussed first and if decided then implemented in another PR as it is a big feature.

**Comment by bbearce** [comment]
All, there is a way to flow up the env variables through a state variable already being used so I caught a ride on the existing process to flow this info up.

**Comment by Didayolo** [comment]
@bbearce I have a doubt: is this PR ready to be reviewed? I think this feature is very important. It may have avoided the congestion we experienced recently.

On a side note, limiting the number of daily submissions per user for a competition when using the default queue could be interesting too.

**Comment by Didayolo** [comment]
@bbearce Can you confirm if this PR is ready or not? Thank you.

**Pull request merged**
