### PR TITLE
Main banner logos (CNRS, LISN, Paris-Saclay)

### PR DESCRIPTION
**Pull request by ihsaan-ullah**
# @ mention of reviewers
@acletournel @Didayolo 

# A brief description of the purpose of the changes contained in this PR.
Main banner now shows clickable logos for
- LISN
- Paris-Saclay
- CNRS

Screenshot 2023-11-10 at 7 45 48 PM

# Issues this PR resolves
- #1185 

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [x] Code review by reviewer
- [x] Hand tested by reviewer
- [x] CircleCi tests are passing
- [x] Ready to merge

### CODE REVIEW

**Comment by ihsaan-ullah** [comment]
Latest upate with white logos

Screenshot 2023-11-10 at 8 20 02 PM

**Comment by acletournel** [comment]
Thanks a lot for the PR. It is nice on chromium, but logos appeared centered, below each other and not resized on firefox (very bug). The rendering on dev tool for smartphone shows the same problem.
with 30% zoom in firefox:
image

**Comment by Didayolo** [comment]
@acletournel @ihsaan-ullah I use Firefox and on my side the display is good:

Capture d’écran 2023-11-10 à 17 13 08

**Comment by ihsaan-ullah** [comment]
For me too everythings is ok

Firefox
firefox

Chrome
chrome

Safari
safari

hopefully collectstatic will fix the sizing issue

**Comment by Didayolo** [comment]
I merged it. @acletournel, please tell us if it's working fine here for you:

- https://codabench-test.lri.fr/

**Pull request merged**
