### PR TITLE
leaderboard scores limited to provided decimal points.

### PR DESCRIPTION
**Pull request by ihsaan-ullah**
# @ mention of reviewers
@Didayolo @bbearce 

# A brief description of the purpose of the changes contained in this PR.
In leaderboard scores are rounded to `precision` decimal points. `precision` can be provided in the yaml file as below

```
leaderboards:
  - index: 0 
    title: Results
    key: main
    submission_rule: "Force_Last"
    columns:
      - index: 0
        title: average auc
        key: auc
        sorting: desc
        precision: 3
      - index: 1
        title: average bac
        key: bac
        sorting: desc
        precision: 4

```

# Issues this PR resolves
Solving the long decimal number for scores in leaderboard

# Screenshot of solved problem
Screenshot 2023-04-07 at 8 02 34 PM

Screenshot 2023-04-07 at 8 02 50 PM

# A checklist for hand testing
- [x] run makemigrations, migrate and collect-static for testing

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [ ] Code review by reviewer
- [ ] Hand tested by reviewer
- [ ] CircleCi tests are passing
- [ ] Ready to merge

### CODE REVIEW

**Comment by Didayolo** [comment]
@ihsaan-ullah 

Do we have also a new field in the editor for the precision?

**Comment by ihsaan-ullah** [comment]
New field in the editor added 
Screenshot 2023-04-13 at 2 48 47 PM

**Comment by ihsaan-ullah** [comment]
I followed these steps and I can see precision :

- pull this branch
- docker down and up
- collect static `docker-compose exec django ./manage.py collectstatic --noinput`
- hard refresh `MAC: command + shift + R`
- uploaded a fresh competition which does not have this field in YAML

Screenshot 2023-04-22 at 5 54 39 PM

**Comment by ihsaan-ullah** [comment]
- [x] Documentation updated for `precision`
- [x] V1 unpacker updated to take into account `numeric_format
- [x] V1 packer tested on [V1 Iris bundle](https://github.com/codalab/competition-examples/tree/master/codalab/Iris)  

#### YAML from Iris bundle:
numeric_format = `2`and `4`  
Screenshot 2023-04-26 at 12 18 52 AM

Converted into precision as shown in the editor:
Screenshot 2023-04-26 at 12 15 01 AM

**Comment by ihsaan-ullah** [comment]
@bbearce 

The rounding to 2 decimal places we added fails in this situation because one of the V1 bundle has `numeric_format` = 4 rather than 2.

What should be done in this case?

**Comment by Didayolo** [comment]
@ihsaan-ullah Your last commit seems a bit strange.

- First, you change a test that was replaced in recent PR (#828, #830)
- Also, it seems that you setup the precision in the test file? That should be done by the bundle no?

**Comment by ihsaan-ullah** [comment]
I changed this function `_run_submission_and_add_to_leaderboard ` to add one more parameter `precision` which by default is 2. In all bundles it is 2 so default value will be used when rounding the score from leaderboard 

Now in the specific case of bundle v15, I passed `precision=4` to the function `_run_submission_and_add_to_leaderboard ` because for this specific bundle precision/numeric_format is `4`. 

I just checked the same file here: https://github.com/codalab/codabench/pull/828 and it looks like the difference is just the addition of `test_v15_iris_result_submission_end_to_end` and `test_v15_iris_code_submission_end_to_end`.


My changes to the test will not affect the new additions as these will use the default parameter `precision=2`.

**Pull request closed without merging**
