### PR TITLE
Analytics snapshot date

### PR DESCRIPTION
**Pull request by ihsaan-ullah**
## Analytics snapshot date PR from Tristan Linked to: #1260

# Description
This is a quick addition to the monitoring tool feature.

It adds the last snapshot date in the analytics view

# Issues this PR resolves
It is a sub task of #713 

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [ ] Code review by reviewer
- [ ] Hand tested by reviewer
- [ ] CircleCi tests are passing
- [ ] Ready to merge

### CODE REVIEW

**Comment by ihsaan-ullah** [comment]
@OhMaley 

While testing this PR locally, I followed the instructions [here](https://github.com/codalab/codabench/wiki/Administrator-procedures#storage-analytics) to create a snapshot manually.

The snapshot is created but the time is not correct. I created at 8:23 PM GMT+5 but it shows 5PM GMT+5

Screenshot 2024-01-04 at 8 24 33 PM

**Comment by bbearce** [comment]
Tested locally and this is what I saw:
* deployed develop and PR
* uploaded comp and submission
* kicked off storage analytics feature snap shot (no data for first one)
* changed my computer's date to the 14th around 1am EST, more precisely 2024-01-14 06:36:44.954147+00 UTC from database. This should be 00:36 on the 14th EST. I'm guessing this gets "rounded up" by the UI.
* re-ran the snap shot
* the storage UI shows:
image

"Last snaphost date: January 13, 2024 at 7:00 PM EST". It is my belief that somehow the 06:36 is being converted to 00:36am on the 14th or 1am. Then back up 6 hours and you get 7pm the day before which is the 13th.

**Comment by ihsaan-ullah** [comment]
@bbearce i will test this one more time locally and then will merge it

**Comment by ihsaan-ullah** [comment]
Tested locally, now the date shown is the correct one.

**Pull request merged**
