### PR TITLE
Competition report icon added

### PR DESCRIPTION
**Pull request by ihsaan-ullah**
# @ mention of reviewers
@Didayolo 

# A brief description of the purpose of the changes contained in this PR.
Now you can see report icon in the competition card in home page and public page
Screenshot 2023-09-22 at 7 40 30 PM
Screenshot 2023-09-22 at 7 27 47 PM

# Issues this PR resolves
- #1170 

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [x] Code review by reviewer
- [x] Hand tested by reviewer
- [x] CircleCi tests are passing
- [x] Ready to merge

### CODE REVIEW

**Comment by Didayolo** [comment]
Excellent 👏

**Comment by Didayolo** [comment]
When I remove the report, the logo is removed in the main page but not in the "public benchmarks" page, even if I hard refresh the page:

Capture d’écran 2023-09-22 à 17 53 20

Capture d’écran 2023-09-22 à 17 53 15

Not sure if its a cache problem or really related to the code

**Comment by Didayolo** [comment]
I think it is related to cache because it is gone when I use another browser

**Comment by ihsaan-ullah** [comment]
> When I remove the report, the logo is removed in the main page but not in the "public benchmarks" page, even if I hard refresh the page:
> 
> Capture d’écran 2023-09-22 à 17 53 20 Capture d’écran 2023-09-22 à 17 53 15
> Not sure if its a cache problem or really related to the code

Can you also change the name to see if this is cache problem

**Comment by Didayolo** [comment]
Indeed the name is not reflected either

**Pull request merged**
