### PR TITLE
Email template fixes

### PR DESCRIPTION
**Pull request by ihsaan-ullah**
# @ mention of reviewers
@Didayolo 

# A brief description of the purpose of the changes contained in this PR.
- Codabench logo was not working in the emails, now fixed
- Slight changes to the email text
- Unsubscribe link removed because we don't have unsubscribe functionality

# Issues this PR resolves
- #1460 

# A checklist for hand testing
We need to deploy this change on codabench test for testing

# Checklist
- [x] Code review by me 
- [ ] Hand tested by me 
- [x] I'm proud of my work
- [x] Code review by reviewer
- [ ] Hand tested by reviewer
- [x] CircleCi tests are passing
- [ ] Ready to merge

### CODE REVIEW

**Comment by Didayolo** [comment]
@ihsaan-ullah Thanks for the PR. Why do we have for each email template a `.html` file and a `.txt` file with the same content?

**Comment by ihsaan-ullah** [comment]
I missed some email templates. Now all ara changed

**Comment by ihsaan-ullah** [comment]
> @ihsaan-ullah Thanks for the PR. Why do we have for each email template a `.html` file and a `.txt` file with the same content?

For some reason, both `txt` and `html` files are used to send the emails
https://github.com/codalab/codabench/blob/a37139a96d7f2beb169b40e9e322453545be5673/src/utils/email.py#L9

**Comment by Didayolo** [comment]
@ihsaan-ullah Deployed on codabench-test.lri.fr

**Comment by ihsaan-ullah** [comment]
Emails sent to participants are working. For some reason I am not receiving admin emails (sent to organizers)

Screenshot 2024-08-22 at 11 05 16 AM
Screenshot 2024-08-22 at 11 06 14 AM
Screenshot 2024-08-22 at 11 06 50 AM

**Comment by ihsaan-ullah** [comment]
We can improve the email design in the future

**Pull request merged**
