### PR TITLE
Poetry error tentative fix

### LINKED ISSUE #1586: Poetry.lock python version error when building codabench
@bbearce 
It seems like there is a problem when trying to build deploy Codabench on the current develop branch:

```python
 => CACHED [django 2/9] RUN apt-get update && apt-get install -y gcc build-essential && rm -rf /var/lib/apt/lists/*                                                                                             0.0s
 => CACHED [django 3/9] RUN curl -sSL https://install.python-poetry.org | python3 -                                                                                                                             0.0s
 => CACHED [django 4/9] RUN poetry config virtualenvs.create false                                                                                                                                              0.0s
 => CACHED [django 5/9] RUN poetry config virtualenvs.in-project false                                                                                                                                          0.0s
 => CACHED [django 6/9] COPY pyproject.toml ./                                                                                                                                                                  0.0s
 => ERROR [django 7/9] RUN poetry lock                                                                                                                                                                          0.7s
------                                                                                                                                                                                                               
 > [django 7/9] RUN poetry lock:                                                                                                                                                                                     
0.513 The currently activated Python version 3.9.20 is not supported by the project (3.9.19).                                                                                                                        
0.513 Trying to find and use a compatible version.                                                                                                                                                                   
0.584                                                                                                                                                                                                                
0.584 Poetry was unable to find a compatible version. If you have one, you can explicitly use it via the "env use" command.                                                                                          
------                                                                                                                                                                                                               
failed to solve: process "/bin/sh -c poetry lock" did not complete successfully: exit code: 1 
```

Looks like an easy fix.

### PR DESCRIPTION
**Pull request by ObadaS**
# @ mention of reviewers
@bbearce @Didayolo 

# A brief description of the purpose of the changes contained in this PR.
This should fix the recent poetry python error.
I also added a fixed version on the poetry installation script, instead of using the latest one (for now it is the latest one though)

# Issues this PR resolves
#1586 

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [x] Code review by reviewer
- [x] Hand tested by reviewer
- [x] CircleCi tests are passing
- [x] Ready to merge

### CODE REVIEW

**Comment by ObadaS** [comment]
The site_worker is shutting down as soon as it launches :
```python
2024-09-19 07:57:58,855: CRITICAL/MainProcess] Unrecoverable error: TypeError('_unpack_version() takes from 1 to 5 positional arguments but 6 were given')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.9/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.9/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 317, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.9/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/tasks.py", line 33, in start
    qos_global = not c.connection.qos_semantics_matches_spec
  File "/usr/local/lib/python3.9/site-packages/kombu/connection.py", line 833, in qos_semantics_matches_spec
    return self.transport.qos_semantics_matches_spec(self.connection)
  File "/usr/local/lib/python3.9/site-packages/kombu/transport/pyamqp.py", line 154, in qos_semantics_matches_spec
    return version_string_as_tuple(props['version']) < (3, 3)
  File "/usr/local/lib/python3.9/site-packages/kombu/utils/text.py", line 49, in version_string_as_tuple
    v = _unpack_version(*s.split('.'))
TypeError: _unpack_version() takes from 1 to 5 positional arguments but 6 were given
[2024-09-19 07:57:58,856: INFO/MainProcess] beat: Shutting down...
```

**Comment by ObadaS** [comment]
It seems like the latest version of RabbitMQ produces the bug mentioned above.
Switching to the previous version, by using `rabbitmq:3.13.7-management` instead of `rabbitmq:management` fixes the problem.

Shouldn't we be using static versions instead of a "modified" latest ?

**Comment by Didayolo** [comment]
Testing locally...

**Comment by Didayolo** [comment]
@ObadaS 

```python
codabench-rabbit-1          | BOOT FAILED
codabench-rabbit-1          | ===========
codabench-rabbit-1          | Error during startup: {error,failed_to_initialize_feature_flags_registry}
codabench-rabbit-1          | 
codabench-rabbit-1          | 2024-10-01 15:58:05.527981+00:00 [error] <0.253.0>   crasher:
codabench-rabbit-1          | 2024-10-01 15:58:05.527981+00:00 [error] <0.253.0>     initial call: application_master:init/4
codabench-rabbit-1          | 2024-10-01 15:58:05.527981+00:00 [error] <0.253.0>     pid: <0.253.0>
codabench-rabbit-1          | 2024-10-01 15:58:05.527981+00:00 [error] <0.253.0>     registered_name: []
codabench-rabbit-1          | 2024-10-01 15:58:05.527981+00:00 [error] <0.253.0>     exception exit: {failed_to_initialize_feature_flags_registry,
codabench-rabbit-1          | 2024-10-01 15:58:05.527981+00:00 [error] <0.253.0>                         {rabbit,start,[normal,[]]}}
codabench-rabbit-1          | 2024-10-01 15:58:05.527981+00:00 [error] <0.253.0>       in function  application_master:init/4 (application_master.erl, line 142)
codabench-rabbit-1          | 2024-10-01 15:58:05.527981+00:00 [error] <0.253.0>     ancestors: [<0.252.0>]
codabench-rabbit-1          | 2024-10-01 15:58:05.527981+00:00 [error] <0.253.0>     message_queue_len: 1
codabench-rabbit-1          | 2024-10-01 15:58:05.527981+00:00 [error] <0.253.0>     messages: [{'EXIT',<0.254.0>,normal}]
codabench-rabbit-1          | 2024-10-01 15:58:05.527981+00:00 [error] <0.253.0>     links: [<0.252.0>,<0.44.0>]
codabench-rabbit-1          | 2024-10-01 15:58:05.527981+00:00 [error] <0.253.0>     dictionary: []
codabench-rabbit-1          | 2024-10-01 15:58:05.527981+00:00 [error] <0.253.0>     trap_exit: true
codabench-rabbit-1          | 2024-10-01 15:58:05.527981+00:00 [error] <0.253.0>     status: running
codabench-rabbit-1          | 2024-10-01 15:58:05.527981+00:00 [error] <0.253.0>     heap_size: 376
codabench-rabbit-1          | 2024-10-01 15:58:05.527981+00:00 [error] <0.253.0>     stack_size: 28
codabench-rabbit-1          | 2024-10-01 15:58:05.527981+00:00 [error] <0.253.0>     reductions: 169
codabench-rabbit-1          | 2024-10-01 15:58:05.527981+00:00 [error] <0.253.0>   neighbours:
codabench-rabbit-1          | 2024-10-01 15:58:05.527981+00:00 [error] <0.253.0> 
codabench-rabbit-1          | 2024-10-01 15:58:05.538831+00:00 [notice] <0.44.0> Application rabbit exited with reason: {failed_to_initialize_feature_flags_registry,{rabbit,start,[normal,[]]}}
codabench-rabbit-1          | Runtime terminating during boot (terminating)
codabench-rabbit-1          | 
codabench-rabbit-1          | Crash dump is being written to: erl_crash.dump...[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
codabench-rabbit-1          | [os_mon] memory supervisor port (memsup): Erlang has closed
codabench-rabbit-1          | =INFO REPORT==== 1-Oct-2024::15:58:07.048064 ===
codabench-rabbit-1          |     alarm_handler: {set,{{disk_almost_full,"/var/lib/rabbitmq"},[]}}
codabench-rabbit-1          | =INFO REPORT==== 1-Oct-2024::15:58:07.051311 ===
codabench-rabbit-1          |     alarm_handler: {set,{system_memory_high_watermark,[]}}
codabench-site_worker-1     | [2024-10-01 15:58:07,249: ERROR/Beat] beat: Connection error: [Errno 111] Connection refused. Trying again in 10.0 seconds...
codabench-compute_worker-1  | [2024-10-01 15:58:07,491: ERROR/MainProcess] consumer: Cannot connect to amqp://rabbit-username:**@rabbit:5672//: [Errno 111] Connection refused.
codabench-compute_worker-1  | Trying again in 8.00 seconds...
codabench-compute_worker-1  | 
```

**Pull request merged**
