### PR TITLE
Competition Whitelist Emails feature

### PR DESCRIPTION
**Pull request by ihsaan-ullah**
# @ mention of reviewers
@Didayolo 

# A brief description of the purpose of the changes contained in this PR.
Now, users can add a list of emails to their competition named `Whitelist Emails`. If this competition is not open i.e. participants are approved by an organizer, then any user whose email is added in whitelist_emails will not require an approval i.e. on register button click, this user will be approved automatically.

# Process

#### Add whitelist emails list
Users can add the whitelist emails list here: Competition -> Edit -> Participation -> Scroll down to white List -> Follow the written instructions

Screenshot 2023-11-12 at 9 17 24 PM

#### Error handling
If a user enters wrong emails, emails are validated and errors are shown
Screenshot 2023-11-12 at 9 18 46 PM

# How to test this feature
1. Add 1 email addresses to the white list like the way described above
2. Make sure to disable auto approve participants
Screenshot 2023-11-12 at 9 19 49 PM

3. Login with the email added in the whitelist, go to the competition registration page and click register, you will see that you are auto approved without the need of an admin to approve you.

# Issues this PR resolves
- #1064 

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [x] Code review by reviewer
- [x] Hand tested by reviewer
- [x] CircleCi tests are passing
- [x] Ready to merge

### CODE REVIEW

**Comment by Didayolo** [comment]
These buttons are the most important settings in this page:

Capture d’écran 2023-11-17 à 16 09 56

Maybe we should put them on top? Or just below "terms"? Because now, with the whitelist taking a lot of space, their hidden at the bottom of the page.

Also, the default vertical size of the whitebox you added could be a bit smaller.

**Comment by ihsaan-ullah** [comment]
Now terms, autoapprove etc are at the top and whitelist at the bottom
Screenshot 2023-11-18 at 6 09 45 PM


Whitelist textarea now does not show status bar and toolbar
Screenshot 2023-11-18 at 6 09 31 PM

**Comment by ihsaan-ullah** [comment]
Remark 2 can be handled in another PR, a lot of work to do for the competition

**Comment by Didayolo** [comment]
@ihsaan-ullah 

I simplified the "note" message. This is ready to be merged, I'll deploy it on the production instance soon.

> Remark 2 can be handled in another PR, a lot of work to do for the competition

I think we can forget about it, it is not useful.

**Comment by lbeziaud** [comment]
@Didayolo The field `whitelist_emails` is currently publicly available which leaks emails. That might be an issue. eg https://www.codabench.org/api/competitions/2178/

**Comment by Didayolo** [comment]
@lbeziaud Good catch. This is indeed a serious problem. Reported here: #1366.

**Pull request merged**
