### PR TITLE
`Release PR#3` created workflow for new releases

### PR DESCRIPTION
**Pull request by ihsaan-ullah**
# @ mention of reviewers
@ObadaS 

# A brief description of the purpose of the changes contained in this PR.
Created a workflow and json file for release information.

# Issues this PR resolves
- #1582 -> Point 4

# A checklist for hand testing
- [ ] We need to test if with a new release publish, this workflow is triggered

# Checklist
- [ ] Hand tested by me 
- [x] CircleCi tests are passing
- [x] Ready to merge

### CODE REVIEW

**Comment by ObadaS** [comment]
Looks good on my end, we only need to test it now

1. I see in the code that you are using `>`, what do you think about using `>>` to have a local file in the repo with all the changes ?
2.  The code doesn't specify a branch, does it push the develop or master branch ? I think we want it to push on the master branch, otherwise we would need to do a separate PR to bring the updated file into master after we already merged into master (since we only publish the Release notes once we have successfully merged into master)

The CircleCI test fails with the same error I have on my local machine when trying to deploy the current develop branch. Seems like there is a problem with the Python version used, which could be an easy fix.

**Comment by ihsaan-ullah** [comment]
> Looks good on my end, we only need to test it now
> 
> 1. I see in the code that you are using `>`, what do you think about using `>>` to have a local file in the repo with all the changes ?

`>` will rewrite the file while `>>` will append. I think we want to rewrite the file


> 2. The code doesn't specify a branch, does it push the develop or master branch ? I think we want it to push on the master branch, otherwise we would need to do a separate PR to bring the updated file into master after we already merged into master (since we only publish the Release notes once we have successfully merged into master)

I have updated the workflow to push changes to `develop` branch and automatically create a PR. We should test it on github if this works or not because I have never worked on workflows. I chose develop branch so that everything is consistent and there is no mismatch between develop and master

**Comment by Didayolo** [comment]
Here, `version.json` looks like this:

```json
{
    "tag_name": "1.1.0",
    "release_name": "Second release",
    "published_at": "November 09, 2023",
    "body": ""
}

However, on the PR#2 (#1592) that'll be merged to develop, we have:

```json
{
  "tag_name": "v1.11.0",
  "release_name": "Release 1.11.0",
  "published_at": "2024-09-16",
  "body": "",
  "release_url": "https://github.com/codalab/codabench/releases/tag/v1.11.0"
}
```

That looks problematic

**Comment by ihsaan-ullah** [comment]
json updated in the latest commit

**Comment by Didayolo** [comment]
So should we merge this to develop? @ihsaan-ullah @ObadaS

**Comment by ihsaan-ullah** [comment]
> So should we merge this to develop? @ihsaan-ullah @ObadaS

@ObadaS do you know when the workflow will be triggered? if this is in develop or master?

**Comment by ObadaS** [comment]
It might not get triggered because the workflow file does not exist yet, and there is nothing that was published after the merge happens. 
But it should trigger automatically, after the merge, when I publish the 1.12 release

**Pull request merged**
