### PR TITLE
competition reward functionality added

### PR DESCRIPTION
**Pull request by ihsaan-ullah**
# @ mention of reviewers
@Didayolo 

# A brief description of the purpose of the changes contained in this PR.
Now users can add reward text to the competition either through the editor or yaml file

# What is done in this PR

- [x] Add/Update reward text 
- [x] Add reward in competition creation and updation
- [x] Add  `reward` in yaml
- [x] update v2 unpacker to unpack `reward`
- [x] Show reward in competition list card

# Screenshots
When `reward` is not added
Screenshot 2023-06-25 at 1 37 28 AM

When reward is added
Screenshot 2023-06-25 at 1 37 46 AM

Competition list shows `reward` icon when competition has reward
Screenshot 2023-06-25 at 2 40 28 AM
Screenshot 2023-06-25 at 2 40 19 AM

# Issues this PR resolves

- #764 -> Editor / YAML fields -> Point 3

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [ ] Code review by reviewer
- [ ] Hand tested by reviewer
- [ ] CircleCi tests are passing
- [ ] Ready to merge

### CODE REVIEW

**Comment by ihsaan-ullah** [comment]
@Didayolo @dtuantran 

I think there is a problem with the `test_db`. https://app.circleci.com/jobs/github/codalab/codabench/3111

In this PR, I just added one field `reward` to the `Competition` model. The tests are failing because each test cannot find `reward` column in the `competition` table.

Do you have any idea why this is happening?

**Comment by Didayolo** [comment]
```python
django.db.utils.ProgrammingError: column competitions_competition.reward does not exist
```

**Comment by Didayolo** [comment]
Related? In productions servers, we have untracked merging of migrations.

Capture d’écran 2023-07-25 à 18 40 04

**Comment by ihsaan-ullah** [comment]
Closing because of the weird issue. Will try in a new branch again

**Pull request closed without merging**
