### PR TITLE
Queue - remove queue from competition when queue is made private

### PR DESCRIPTION
**Pull request by ihsaan-ullah**
# @ mention of reviewers
@Didayolo 

# A brief description of the purpose of the changes contained in this PR.
When a user's public Queue is updated to private, remove it from all competitions which do not belong to this user.

# Issues this PR resolves
- #1014 

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [ ] Code review by reviewer
- [ ] Hand tested by reviewer
- [ ] CircleCi tests are passing
- [ ] Ready to merge

### CODE REVIEW

**Comment by Didayolo** [comment]
Steps to test:


- Make a queue public
- Another user add the queue to its benchmark as the queue is public
- Make the queue private
- The queue should be back to default in the benchmark

**Comment by Didayolo** [comment]
@ihsaan-ullah 

Strange behavior observed:

- User 1 make a queue public
- User 2 uses it in a bechmark
- User 1 make the queue private
- Now the queue is removed from User 2 benchmark (back to default, the expected behavior). HOWEVER, User 2 can select again the queue and save the change. It is as if, once a queue is public, it can also be found to use it in any benchmark.

Another test, no problematic behavior:
- User 1 creates a private queue
- User 2 cannot find it in the editor (excepted behavior)

**Comment by ihsaan-ullah** [comment]
> @ihsaan-ullah
> 
> Strange behavior observed:
> 
> * User 1 make a queue public
> * User 2 uses it in a bechmark
> * User 1 make the queue private
> * Now the queue is removed from User 2 benchmark (back to default, the expected behavior). HOWEVER, User 2 can select again the queue and save the change. It is as if, once a queue is public, it can also be found to use it in any benchmark.

This is very strange. Checking this

**Comment by ihsaan-ullah** [comment]
@Didayolo with latest push that issue should be gone

**Comment by Didayolo** [comment]
Interesting, I'll test this asap

**Pull request merged**
