### PR TITLE
Update Python using Poetry (Issue #1413)

### PR DESCRIPTION
**Pull request by bbearce**
### Reviewers
@Didayolo, @ihsaan-ullah

### Summary
Meant to transition us to poetry from pip dependency management. I only upped the python version to 3.9 and not even for all Dockerfiles. I ran into issues using python3.10. There are too many changes in a variety of packages. I think the only real way to do this is one package at a time and slowly over time bump up the python. For now I really just switched us to poetry from pip but kept the same packages versions. I think I changed one called ipdb and upgraded a bit because python 3.9 required it.

Dockerfiles updated:
* Dockerfile
```
docker build --no-cache -f Dockerfile -t codabench-django:latest ./
```
* Dockerfile.compute_worker
```

docker build --no-cache -f Dockerfile.compute_worker -t codabench-compute_worker:latest ./
```

* Dockerfile.compute_worker_gpu
```
docker build --no-cache -f Dockerfile.compute_worker_gpu -t codabench-compute_worker_gpu:latest ./
```

* Dockerfile.flower
```
docker build --no-cache -f Dockerfile.flower -t codabench-flower:latest ./
```

**PS: Do we use Dockerfile.celery at all?**

### Issues this PR resolves
- #1413

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [x] Code review by reviewer
- [x] Hand tested by reviewer
- [x] CircleCi tests are passing
- [x] Ready to merge

### CODE REVIEW

**Comment by Didayolo** [comment]
Nice progress. This is a fundamental change that needs to be tested deeply before merging.

**Comment by ihsaan-ullah** [comment]
Nice work done @bbearce. I see that there is poetry for compute worker. Will this affect the setting up of a compute worker?
https://github.com/codalab/codabench/wiki/Compute-Worker-Management---Setup

**Comment by Didayolo** [comment]
Also, what is the file `compute_worker/poetry.lock` ?

**Comment by Didayolo** [comment]
We are supposed to remove the requirements.txt files in this PR

**Comment by Didayolo** [comment]
This currently runs on https://codabench-test.lri.fr/

We need also to test compute workers

**Comment by bbearce** [comment]
Was working on this over the weekend. A couple questions.
* I had to delete basically every docker image to build the gpu one. Could we request maybe 50GB total for this VM?
* The compute worker and gpu worker both start from the same python3.9 and I believe that is for consistency. However installing cuda drivers and nvidia-toolkit is harder that way. I have a current Dockerfile I'm working on and it builds to about ~8GB but it starts from image ubuntu:20.04. Can we start from ubuntu or even better yet, nvidia-cuda images? Adding python after the fact is easy and I could even integrate pyenv, though don't want to go too crazy.
  - The obvious con is that it wouldn't be the same base image as the compute worker, unless we switched that to come from ubuntu:20.04 as well (just skip cuda installation).

What do you think?

**Comment by ihsaan-ullah** [comment]
If you want to use a cuda image, you can check this one which we are using in another project

https://github.com/FAIR-Universe/HEP-Challenge/blob/master/docker/Dockerfile

**Comment by bbearce** [comment]
Exactly. The more I think about it, this is great but how much should the gpu worker and the cpu worker match (Dockerfile wise)? My take is that you'd want them to be as similar as possible and I'm a worried using an nvidia image for the cpu worker doesn't make sense so then these would come from different bases. Does anyone else think having both workers start from ubuntu is too low level?

PS: Totally down to do an nvidia image for gpu worker and python or ubuntu for cpu worker if folks don't think the different base matters much. Would greatly simplify gpu setup, effectively allowing us to skip cuda install altogether.

**Comment by Didayolo** [comment]
> Totally down to do an nvidia image for gpu worker and python or ubuntu for cpu worker if folks don't think the different base matters much. Would greatly simplify gpu setup, effectively allowing us to skip cuda install altogether.

Yeah I guess we can go for this

**Comment by Didayolo** [comment]
We updated the compute worker docker images:
- tag `test` for testing CPU
- tag `gpu` for GPU version

The CPU one is currently running submissions on the test server without problems.

We are in the process of testing the GPU version.

**Comment by Didayolo** [comment]
Testing the GPU compute worker, I get this error on a submission of the "GPU test" bundle:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/compute_worker.py", line 115, in run_wrapper
    run.prepare()
  File "/compute_worker.py", line 803, in prepare
    self._get_container_image(self.container_image)
  File "/compute_worker.py", line 367, in _get_container_image
    container_engine_pull = check_output(cmd)
  File "/usr/local/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nvidia-docker'
```

**Comment by Didayolo** [comment]
Now the CPU version is broken...

```python
[2024-06-19 19:26:28,933: INFO/ForkPoolWorker-1] Connecting to wss://codabench-test.lri.fr/submission_input/6/797/d3673c8d-e345-4f34-aa44-73e01e63c530/
[2024-06-19 19:26:31,802: WARNING/ForkPoolWorker-1] WS: b'docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].\n'
[2024-06-19 19:26:31,802: INFO/ForkPoolWorker-1] Process exited with 125
[2024-06-19 19:26:31,802: INFO/ForkPoolWorker-1] Disconnecting from websocket wss://codabench-test.lri.fr/submission_input/6/797/d3673c8d-e345-4f34-aa44-73e01e63c530/
[2024-06-19 19:26:33,936: INFO/ForkPoolWorker-1] [exited with 125]
[2024-06-19 19:26:33,936: INFO/ForkPoolWorker-1] [stderr]
b'docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].\n'
[2024-06-19 19:26:33,936: INFO/ForkPoolWorker-1] Putting raw data b'docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].\n' in https://minio-test.lri.fr/codabench-private/submission_details/2024-06-19-1718825186/183b292a2ba8/scoring_stderr.txt?AWSAccessKeyId=AKIAIOSFODNN7EXAMPLE&Signature=08Orj1ptjBxO7cguAlMCA83YwGs%3D&content-type=application%2Fzip&Expires=1718911586
```

The code in `compute_worker.py`:

```python
        engine_cmd = [
            CONTAINER_ENGINE_EXECUTABLE,
            'run',
            # Remove it after run
            '--rm',
            f'--name={self.ingestion_container_name if kind == "ingestion" else self.program_container_name}',

            # Don't allow subprocesses to raise privileges
            '--security-opt=no-new-privileges',

            # GPU or not
            '--gpus', 
            'all' if os.environ.get("USE_GPU") else '0',

            # Set the volumes
            '-v', f'{self._get_host_path(program_dir)}:/app/program',
            '-v', f'{self._get_host_path(self.output_dir)}:/app/output',
            '-v', f'{self.data_dir}:/app/data:ro',

            # Start in the right directory
            '-w', '/app/program',

            # Don't buffer python output, so we don't lose any
            '-e', 'PYTHONUNBUFFERED=1',
        ]
```

**Comment by Didayolo** [comment]
Fixed!

**Pull request merged**
