### PR TITLE
Submission remove from leaderboard - Empty error

### PR DESCRIPTION
**Pull request by ihsaan-ullah**
# @ mention of reviewers
@Didayolo 

# A brief description of the purpose of the changes contained in this PR.
There was an empty error shown when someone wanted to remove a submission from leaderboard. Now an error message is displayed along with correction in the logic.

# Issues this PR resolves
- #1125 
- #1325 

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [x] Code review by reviewer
- [ ] Hand tested by reviewer
- [x] CircleCi tests are passing
- [ ] Ready to merge

### CODE REVIEW

**Comment by Didayolo** [comment]
Good job. It is very nice that you are adding comments, cleaning the form of the code and **adding tests**. Very good coding practices.

**Comment by Didayolo** [comment]
@ihsaan-ullah 

It seems that I still have an error message when trying to add a submission to leaderboard when "Force last" is enabled:

Capture d’écran 2024-02-15 à 17 18 02

Capture d’écran 2024-02-15 à 17 17 58

**Comment by Didayolo** [comment]
When removing a submission, it depends:
- As an organizer / admin, I get the new error message ("You are not allowed [...]")
- As a simple participant, I get no error message

**Comment by ihsaan-ullah** [comment]
> @ihsaan-ullah
> 
> It seems that I still have an error message when trying to **add** a submission to leaderboard when "Force last" is enabled:
> 
> Capture d’écran 2024-02-15 à 17 18 02 Capture d’écran 2024-02-15 à 17 17 58
> When **removing** a submission, it depends:
> 
> * As an organizer / admin, I get the new error message ("You are not allowed [...]")
> * As a simple participant, I get no error message

I will check this, i did not know that a simple participant can also do this. I tested it in the admin interface only

**Comment by ihsaan-ullah** [comment]
@Didayolo now it should be ok

**Comment by Didayolo** [comment]
Perfect

**Pull request merged**
