### PR TITLE
Detailed results displayed for each task on leaderboard

### LINKED ISSUE #907: Shouldn't have task have a "detailed results" column?

### PR DESCRIPTION
**Pull request by ihsaan-ullah**
# @ mention of reviewers
@Didayolo 

# A brief description of the purpose of the changes contained in this PR.
Now users can see detailed results for each task in leaderboard
Screenshot 2023-06-20 at 6 32 19 AM

# Issues this PR resolves

- #907 

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [x] Code review by reviewer
- [x] Hand tested by reviewer
- [x] CircleCi tests are passing
- [x] Ready to merge

### CODE REVIEW

**Comment by Didayolo** [comment]
@ihsaan-ullah 

It looks like `Fact Sheet Answers` is considered as a task and have it's own link for detailed results (which results, unsurprisingly, to a 404 error):

Capture d’écran 2023-07-11 à 17 33 11

This column should not be created.

**Comment by ktgiahieu** [comment]
@ihsaan-ullah  @Didayolo 

How can I help you test it and make the required modification? In principle, we are opening our competition on Monday, and it will be confusing to users if they don't get the proper feedback.

**Comment by ihsaan-ullah** [comment]
@Didayolo with the latest push the problem should be fixed. 

Here is a screenshot
Screenshot 2023-07-21 at 6 30 00 PM

**Comment by ihsaan-ullah** [comment]
> @ihsaan-ullah @Didayolo
> 
> How can I help you test it and make the required modification? In principle, we are opening our competition on Monday, and it will be confusing to users if they don't get the proper feedback.

@ktgiahieu If you want to test this locally, you can start with these instructions :
https://github.com/codalab/codabench/wiki/Codabench-Installation

switch to this branch before testing

**Comment by Didayolo** [comment]
@ktgiahieu The change is now merged on develop, but still not deployed on production.

We'll deploy it on the [test server](https://codabench-test.lri.fr/) first, where you'll be able to test the feature and confirm it is working well before we merge into master (and the [main server](https://www.codabench.org/)).

Right now we have a problem with the deployment on the test server, I'll let you know when it is ready.

**Pull request merged**
