### PR TITLE
`Release PR#1` - Display release version in Codabench footer

### PR DESCRIPTION
**Pull request by ihsaan-ullah**
# @ mention of reviewers
@Didayolo

# A brief description of the purpose of the changes contained in this PR.
Now we can display release version in the header just below the main logo
Screenshot 2024-09-14 at 11 20 35 PM

# Issues this PR resolves
- #1582 -> Point 1, 2

# A checklist for hand testing
- [ ] collectstatic and check that the current version is displayed correctly

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [x] Code review by reviewer
- [x] Hand tested by reviewer
- [x] CircleCi tests are passing
- [x] Ready to merge

### CODE REVIEW

**Comment by ObadaS** [comment]
This looks pretty good in my opinion.

How much more work would it be to make this clickable, bringing to the Github release ?
Also, can it automatically go fetch the version number in the `version.json` file you created from #1584 ?
From what I see, we have to manually change it after each update if we keep everything like this, right ?

**Comment by Didayolo** [comment]
Hi @ihsaan-ullah, thanks for the PR. I think this is too much visible. We should put it at the bottom of the page in my opinion. Also it could be added to `base.html` to appear in every pages on the bottom banner.

Capture d’écran 2024-09-16 à 20 53 20

**Comment by ihsaan-ullah** [comment]
Version moved to footer and is not clickable

Screenshot 2024-09-17 at 11 40 43 AM

**Comment by Didayolo** [comment]
@ihsaan-ullah Very good. Are we still waiting the addition of a json file before merging this?

**Comment by ihsaan-ullah** [comment]
> @ihsaan-ullah Very good. Are we still waiting the addition of a json file before merging this?

You can merge this one. I will handle the json file in another PR

**Pull request merged**
