### PR TITLE
Contact Email, Competition reward, Challenge report

### PR DESCRIPTION
**Pull request by ihsaan-ullah**
# @ mention of reviewers
@Didayolo 

# A brief description of the purpose of the changes contained in this PR.
Now users can add the following to their competition

1. contact email
2. reward text 
3. report link 

# What is done in this PR

- [x] Add/Update contact email
- [x] Add/Update reward text 
- [x] Add/Update report link
- [x] Add these in competition creation and updation
- [x] Add `contact_email` and `reward` in yaml
- [x] update v2 unpacker to unpack `contact_email` and `reward`
- [x] show `contact_email` in forum
- [x] Show reward in competition list card

# Screenshots
When `contact email`,`reward`, and `report` are not added
Screenshot 2023-06-25 at 1 37 28 AM

When all of these are added
Screenshot 2023-06-25 at 1 37 46 AM

These can be added in the editor
Screenshot 2023-06-25 at 1 37 58 AM

YAML file can have `contact_email` and `reward` as shown below 
Screenshot 2023-06-25 at 1 51 02 AM

Competition unpacked using V2 unpacker using the above YAML
Screenshot 2023-06-25 at 1 54 10 AM

Contact email in forum
Screenshot 2023-06-25 at 2 23 20 AM

Competition list shows `reward` icon when competition has reward
Screenshot 2023-06-25 at 2 40 28 AM
Screenshot 2023-06-25 at 2 40 19 AM

# Issues this PR resolves

- #764 -> Editor / YAML fields -> Point 2,3,4

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [ ] Code review by reviewer
- [ ] Hand tested by reviewer
- [ ] CircleCi tests are passing
- [ ] Ready to merge

### CODE REVIEW

**Comment by ihsaan-ullah** [comment]
@Didayolo @dtuantran 

I don't know why these tests are failing. 

I see that while fetching competitions, it says that column `contact_email` does not exist. But I have added the migration file in the PR and it should work.

```
ql = 'SELECT "competitions_competition"."id", "competitions_competition"."chahub_timestamp", "competitions_competition"."ch...", "competitions_competition"."report" FROM "competitions_competition" WHERE "competitions_competition"."deleted" = %s'
params = (False,)
ignored_wrapper_args = (False, {'connection': <django.db.backends.postgresql.base.DatabaseWrapper object at 0x7fa4dd53a460>, 'cursor': <django.db.backends.utils.CursorWrapper object at 0x7fa4d9e854c0>})

    def _execute(self, sql, params, *ignored_wrapper_args):
        self.db.validate_no_broken_transaction()
        with self.db.wrap_database_errors:
            if params is None:
                return self.cursor.execute(sql)
            else:
>               return self.cursor.execute(sql, params)
E               psycopg2.errors.UndefinedColumn: column competitions_competition.contact_email does not exist
E               LINE 1: ...n_type", "competitions_competition"."fact_sheet", "competiti...
E                                                                            ^

/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py:84: UndefinedColumn
```

**Comment by ihsaan-ullah** [comment]
Screenshot 2023-06-26 at 6 31 33 PM

> Maybe the display of the reward should be in the same style as "Participants" and "Submissions" counter? (top right of the page)

Adrien, just the style? Because if we want to change the place,the text will not fit there 

> The styling of the contact address does not fit, especially because it is not the same blue as other links

I will change the color.

> The CircleCI tests are not passing

About the tests, it is giving me an error which is not supposed to happen. I left a comment for you and Tuan to check what could be the problem

**Comment by Didayolo** [comment]
@ihsaan-ullah Aren't you on vacation? I appreciate your engagement, but don't forget to take a break. You don't need to answer to these notifications while on vacation :-)

**Comment by ihsaan-ullah** [comment]
> @ihsaan-ullah Aren't you on vacation? I appreciate your engagement, but don't forget to take a break. You don't need to answer to these notifications while on vacation :-)

I will go this week :D

**Comment by Didayolo** [comment]
> I will go this week :D

Nice.

>  just the style? Because if we want to change the place,the text will not fit there

Yes I meant the style and the position. It would be below the too other blocks, maybe in orange or yellow.

> I will change the color.

Shouldn't it be linked to another already existing CSS class?

**Comment by ihsaan-ullah** [comment]
Style can be changed, but the position will be complicated because it has just this much space in the screenshot

Screenshot 2023-06-26 at 6 59 09 PM

**Comment by Didayolo** [comment]
Then you can keep it as it is right now. The style is cool and it is well visible, so it differentiate well between competition with prize and without prize.

**Comment by ihsaan-ullah** [comment]
Screenshot 2023-06-27 at 2 17 32 PM

Contact email color

**Comment by Didayolo** [comment]
Just a side note, for now and for the future: when we modify things in the editor (and yaml), we should also check that the manual competition creation is working fine with the new fields.

**Comment by ihsaan-ullah** [comment]
Closing this PR. I will start a new one to see why circle ci tests are failing

**Pull request closed without merging**
