### PR TITLE
Server status - Rabbit MQ and Flower links fixed

### PR DESCRIPTION
**Pull request by ihsaan-ullah**
# @ mention of reviewers
@Didayolo 

# A brief description of the purpose of the changes contained in this PR.
Now Rabbit MQ and Flower links point to the right URL as mentioned here: https://github.com/codalab/codabench/wiki/Administrator-procedures

# Issues this PR resolves
- #1105 

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [x] Code review by reviewer
- [x] Hand tested by reviewer
- [x] CircleCi tests are passing
- [x] Ready to merge

### CODE REVIEW

**Comment by Didayolo** [comment]
@ihsaan-ullah After deploying this in codabench-test server, the links are:

- localhost:15672
- localhost:5555

Therefore it is not working

**Comment by ihsaan-ullah** [comment]
Can you please check in the `.env` what is in this variable `DOMAIN_NAME`

**Comment by Didayolo** [comment]
But you are using `SITE_DOMAIN` the code

**Comment by ihsaan-ullah** [comment]
> ```
> DOMAIN_NAME=codabench-test.lri.fr:80
> ```

perfect. pushing a new branch which will fix this

**Comment by Didayolo** [comment]
I restored this branch but you can create a new one

**Pull request merged**
