### PR TITLE
Updated `bpython` to fix shell_plus error

### PR DESCRIPTION
**Pull request by ihsaan-ullah**
# @ mention of reviewers
@Didayolo @bbearce 

Benjamin I deleted the lock file because there was no way to generate the file. Docker build was failing with any change in the toml file.

# A brief description of the purpose of the changes contained in this PR.
- Deleted `poetry.lock` file because when we make changes to package versions in `pyproject.toml` we need to regenerate it
- In `pyproject.toml` updated python version to 3.9  to fix the inconsistency with dockerfile and bpython version to fix shell_plus error
- In `Dockerfile` removed copy `poetry.lock` command and added poetry lock command to generate lock file

# Issues this PR resolves
- #1537 
- #1530 

# A checklist for hand testing
- [x] rebuild django and site worker and make sure everything is ok in the logs
- [x] run `docker-compose exec django ./manage.py shell_plus` without any error

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [x] Code review by reviewer
- [x] Hand tested by reviewer
- [x] CircleCi tests are passing
- [x] Ready to merge

### CODE REVIEW

**Comment by ihsaan-ullah** [comment]
We should document the following 

# How to update packages
1. Update package version in `pyproject.toml`
2. Rebuild django container
```
docker build --no-cache -f Dockerfile -t codabench-django:latest ./
```
3. Rebuild site_worker container
```
docker build --no-cache -f Dockerfile -t codabench-site_worker:latest ./
```

NOTE: every time you build these containers, a fresh `poetry.lock` file is generated in the container which is then used to install packages.

**Comment by Didayolo** [comment]
I get this error after running `docker compose up -d`:

```python
 => [codabench-django 2/9] RUN apt-get update && apt-get install -y gcc build-essential && rm -rf /var/lib/apt/lists/*                                                                                11.2s
 => ERROR [codabench-flower  4/10] RUN curl -sSL https://install.python-poetry.org | python3 -                                                                                                        81.4s
 => [codabench-django 3/9] RUN curl -sSL https://install.python-poetry.org | python3 -                                                                                                                64.6s
 => [codabench-site_worker 4/9] RUN poetry config virtualenvs.create false                                                                                                                             0.6s
 => [codabench-django 5/9] RUN poetry config virtualenvs.in-project false                                                                                                                              0.6s
 => [codabench-django 6/9] COPY pyproject.toml ./                                                                                                                                                      0.0s
 => CANCELED [codabench-django 7/9] RUN poetry lock                                                                                                                                                    9.1s
------
 > [codabench-flower  4/10] RUN curl -sSL https://install.python-poetry.org | python3 -:
#0 81.21 Retrieving Poetry metadata
#0 81.21 
#0 81.21 # Welcome to Poetry!
#0 81.21 
#0 81.21 This will download and install the latest version of Poetry,
#0 81.21 a dependency and package manager for Python.
#0 81.21 
#0 81.21 It will add the `poetry` command to Poetry's bin directory, located at:
#0 81.21 
#0 81.21 /root/.local/bin
#0 81.21 
#0 81.21 You can uninstall at any time by executing this script with the --uninstall option,
#0 81.21 and these changes will be reverted.
#0 81.21 
#0 81.21 Installing Poetry (1.8.3)
#0 81.21 Installing Poetry (1.8.3): Creating environment
#0 81.21 Installing Poetry (1.8.3): Installing Poetry
#0 81.21 Installing Poetry (1.8.3): An error occurred. Removing partial environment.
#0 81.21 Poetry installation failed.
#0 81.21 See /poetry-installer-error-paxk7uql.log for error logs.
------
failed to solve: executor failed running [/bin/sh -c curl -sSL https://install.python-poetry.org | python3 -]: exit code: 1
```

**Comment by Didayolo** [comment]
I get the following error after running `docker compose up -d`:

```python
 => CANCELED [codabench-compute_worker 2/9] RUN apt-get update && curl -fsSL https://get.docker.com | sh                                                                                              41.1s
 => [codabench-flower  1/10] FROM docker.io/library/python:3.9-alpine@sha256:3beee521e2eec6a3a9ba0c2fdac1bf30969e7f275e379f5b0dd8b45b25f50955                                                          0.0s
 => => resolve docker.io/library/python:3.9-alpine@sha256:3beee521e2eec6a3a9ba0c2fdac1bf30969e7f275e379f5b0dd8b45b25f50955                                                                             0.0s
 => CACHED [codabench-flower  2/10] RUN apk add --no-cache ca-certificates && update-ca-certificates curl                                                                                              0.0s
 => CACHED [codabench-flower  3/10] RUN apk add curl                                                                                                                                                   0.0s
 => ERROR [codabench-flower  4/10] RUN curl -sSL https://install.python-poetry.org | python3 -                                                                                                        40.5s
------                                                                                                                                                                                                      
 > [codabench-flower  4/10] RUN curl -sSL https://install.python-poetry.org | python3 -:                                                                                                                    
#0 40.37 Retrieving Poetry metadata                                                                                                                                                                         
#0 40.37                                                                                                                                                                                                    
#0 40.37 # Welcome to Poetry!                                                                                                                                                                               
#0 40.37                                                                                                                                                                                                    
#0 40.37 This will download and install the latest version of Poetry,                                                                                                                                       
#0 40.37 a dependency and package manager for Python.                                                                                                                                                       
#0 40.37                                                                                                                                                                                                    
#0 40.37 It will add the `poetry` command to Poetry's bin directory, located at:                                                                                                                            
#0 40.37                                                                                                                                                                                                    
#0 40.37 /root/.local/bin                                                                                                                                                                                   
#0 40.37 
#0 40.37 You can uninstall at any time by executing this script with the --uninstall option,
#0 40.37 and these changes will be reverted.
#0 40.37 
#0 40.37 Installing Poetry (1.8.3)
#0 40.37 Installing Poetry (1.8.3): Creating environment
#0 40.37 Installing Poetry (1.8.3): Installing Poetry
#0 40.37 Installing Poetry (1.8.3): An error occurred. Removing partial environment.
#0 40.37 Poetry installation failed.
#0 40.37 See /poetry-installer-error-8ei1b6ej.log for error logs.
------
failed to solve: executor failed running [/bin/sh -c curl -sSL https://install.python-poetry.org | python3 -]: exit code: 1
```

**Comment by ihsaan-ullah** [comment]
looks like this is a problem from `flower`. You need this dockerfile
https://github.com/codalab/codabench/pull/1520

**Comment by Didayolo** [comment]
> looks like this is a problem from `flower`. You need this dockerfile: #1520

Oh yeah I did not realize the order of the PR. Thanks.

**Comment by Didayolo** [comment]
Working fine!

**Pull request merged**
