### PR TITLE
Convert orphan files deletion task to async using celery task. Update celery config to make it possible

### PR DESCRIPTION
**Pull request by Didayolo**
# Original PR

- #1597

# Description 

Make the orphan files deletion task asynchronous.
This comes with few changes to make it possible:
- Enable the backend results of the celery tasks. This allows to store the states of any celery tasks. We use this to check is the task is running or not
- upgrade the celery package to the closest version that fixes a known bug on incompatible version with python 3.9 that manifests only when working with celery task results
- Fixes the patch number of the python version in the Dockerfile to match the one in the pyproject.toml file (else poetry won't be happy)
- Add an API route to check the status of the orphan files deletion task
- Update the frontend to reflect the status of the deletion task

# For testing
Do not forget to build the docker images !

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [x] Code review by reviewer
- [x] Hand tested by reviewer
- [x] CircleCi tests are passing
- [ ] Ready to merge

### CODE REVIEW

**Comment by Didayolo** [comment]
@OhMaley Error during the building:

```python
=> ERROR [site_worker 7/9] RUN poetry lock                                1.7s
 => CANCELED [flower 7/9] RUN poetry add redis=3.0.1                       0.7s
------
 > [site_worker 7/9] RUN poetry lock:
1.366 The currently activated Python version 3.9.19 is not supported by the project (3.9.20).
1.366 Trying to find and use a compatible version. 
1.534 
1.535 Poetry was unable to find a compatible version. If you have one, you can explicitly use it via the "env use" command.
------
failed to solve: process "/bin/sh -c poetry lock" did not complete successfully: exit code: 1

Exited with code exit status 17
```

Any thoughts?

**Comment by OhMaley** [comment]
Oui il faut que la version de python noté dans le Dockerfile et dans pyproject.toml soit identique.
Je l'ai update dans le dockerfile mais être la même version que celle du pyproject.toml, mais ce dernier fichier a été mis à jour il y a 4h on dirai

**Comment by Didayolo** [comment]
Ce qui m'étonne c'est que je suis reparti de `develop` à l'instant. Mais ça devrait être bon maintenant j'imagine.

**Comment by bbearce** [comment]
```bash
pyenv install 3.9.20
pyenv virtualenv 3.9.20 codabench_django
pyenv activate codabench_django
# pyenv uninstall codabench_django
poetry config virtualenvs.create false
poetry config virtualenvs.in-project false
poetry install # installs from lock file
```

**Pull request merged**
