### PR TITLE
Submit as organization made clear

### PR DESCRIPTION
**Pull request by ihsaan-ullah**
# @ mention of reviewers
@Didayolo 

# A brief description of the purpose of the changes contained in this PR.
Now users can see a message and link to create organization when no organization has been created

No organization
Screenshot 2023-06-22 at 1 48 06 PM

Has organization
Screenshot 2023-06-22 at 1 47 38 PM

# Issues this PR resolves
- #964 

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [x] Code review by reviewer
- [x] Hand tested by reviewer
- [x] CircleCi tests are passing
- [x] Ready to merge

### CODE REVIEW

**Comment by Didayolo** [comment]
In my opinion it would be better if `create organization` is shown only when you click on the bar, like this:

Capture d’écran 2023-06-22 à 13 20 21

Capture d’écran 2023-06-22 à 13 20 28

It is sufficient to make it clear and it avoids cluttering the interface.

**Comment by ihsaan-ullah** [comment]
I am not sure if a dropdown can be used like this.

**Comment by Didayolo** [comment]
OK.

Also, the link is not displayed if you have already created an organization (which is what we want indeed). But is it displayed when you are part of an organization you did not create? I guess you should be able to submit as an organization you are part of, and the link should not be shown then.

**Comment by ihsaan-ullah** [comment]
Trying to achieve this
Screenshot 2023-06-22 at 4 54 41 PM

**Comment by Didayolo** [comment]
OK. If it is too complicated, don't spend too much time on this I guess :-)

**Comment by ihsaan-ullah** [comment]
Screenshot 2023-06-22 at 5 38 41 PM


Screenshot 2023-06-22 at 5 38 55 PM


I confirm that in the dropdown we can only see organizations you have created. Other organizations where you are invited are not shown

**Comment by Didayolo** [comment]
Very nice changes! The use of the question mark is clearly smoother.

> I confirm that in the dropdown we can only see organizations you have created. Other organizations where you are invited are not shown

OK, I guess this is a separate issue. The organization system is not completely done apparently.

**Comment by ihsaan-ullah** [comment]
If an organization is used in a submission, it cannot be deleted. Is this what we want?

If not then this filed should be updated: 
https://github.com/codalab/codabench/blob/e9f7ef41ab331c95027e2774a977eb951b3b45c9/src/apps/competitions/models.py#L426

**Comment by Didayolo** [comment]
> If an organization is used in a submission, it cannot be deleted. Is this what we want?

I think we always want to be able to delete submissions. However, I'm not sure how this should be managed. Indeed, it is also a separate issue. Maybe we need a general issue about organization to brainstorm a bit. We can use this one:

- #805

**Pull request merged**
