### PR TITLE
Optimization `PR#2` - Submissions and Participants Count

### PR DESCRIPTION
**Pull request by ihsaan-ullah**
# @ mention of reviewers
@Didayolo 

# A brief description of the purpose of the changes contained in this PR.
This is a first PR in the optimization effort to load codabench quickly. The following are done in this PR:

1. Adde new fields to competition modal `participants_count` and `submissions_count`
2. Used these fields in the competition detail page
3. Used `participants_count` field in public competitions page
4. Used `participants_count` field in the popular competitions section in home page

On the backend, serializers are changed to use this new filed instead of the annotated values from the queries.

#### **NOTE**

1. when you upload a new submission, `submissions_count` will be updated (+1)
2. When you delete a submission, `submissions_count` will be updated (-1)
3. When a new participant joins the competition (even not approved yet) the `participants_count` will update (+1)
4. `participants_count` is never decremented because we do not delete a participant we only revoke the status

# Manual update

**1. Migration**
```sh
docker compose exec django ./manage.py migrate
```

**2. Update counts for all competitions**

Bash into django console
```
docker compose exec django ./manage.py shell_plus
```

Import and call the function
```python
from competitions.submission_participant_counts import compute_submissions_participants_counts
compute_submissions_participants_counts()
```

# Issues this PR resolves
- #1327 -> `Submissions and Participants`

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [x] Code review by reviewer
- [x] Hand tested by reviewer
- [x] CircleCi tests are passing
- [x] Ready to merge

### CODE REVIEW

**Comment by Didayolo** [comment]
Very nice work. I'll review it asap.

**Comment by Didayolo** [comment]
@ihsaan-ullah Any idea why your change triggers the following error?

```python
=================================== FAILURES ===================================
____________ SubmissionMixinTests.test_invalid_submission_not_sent _____________

self = <chahub.tests.test_chahub_mixin.SubmissionMixinTests testMethod=test_invalid_submission_not_sent>

    def test_invalid_submission_not_sent(self):
        self.submission.status = "Running"
        self.submission.is_public = False
        resp1 = self.mock_chahub_save(self.submission)
>       assert not resp1.called
E       AssertionError: assert not True
E        +  where True = <MagicMock name='_send' id='139945117507488'>.called

src/apps/chahub/tests/test_chahub_mixin.py:49: AssertionError
----------------------------- Captured stderr call -----------------------------
ChaHub :: Submission(224) is_valid = False
ChaHub :: Competition(161) is_valid = True
ChaHub :: Received response 201 
Task chahub.tasks.send_to_chahub[2ffe7de6-212d-47c6-b4c1-fc6971c5ab19] succeeded in 0.004535872000019481s: None
------------------------------ Captured log call -------------------------------
INFO     chahub.models:models.py:122 ChaHub :: Submission(224) is_valid = False
INFO     chahub.models:models.py:122 ChaHub :: Competition(161) is_valid = True
INFO     chahub.tasks:tasks.py:56 ChaHub :: Received response 201 
INFO     celery.app.trace:trace.py:125 Task chahub.tasks.send_to_chahub[2ffe7de6-212d-47c6-b4c1-fc6971c5ab19] succeeded in 0.004535872000019481s: None
____ SubmissionMixinTests.test_retrying_invalid_submission_wont_retry_again ____

self = <chahub.tests.test_chahub_mixin.SubmissionMixinTests testMethod=test_retrying_invalid_submission_wont_retry_again>

    def test_retrying_invalid_submission_wont_retry_again(self):
        self.submission.status = "Running"
        self.submission.chahub_needs_retry = True
        resp = self.mock_chahub_save(self.submission)
>       assert not resp.called
E       AssertionError: assert not True
E        +  where True = <MagicMock name='_send' id='139945080014256'>.called

src/apps/chahub/tests/test_chahub_mixin.py:59: AssertionError
```

**Comment by ihsaan-ullah** [comment]
@Didayolo I think these tests are useless because they are supposed to send submissions to ChaHub but there is not ChaHub right?

**Comment by Didayolo** [comment]
> @Didayolo I think these tests are useless because they are supposed to send submissions to ChaHub but there is not ChaHub right?

@ihsaan-ullah That is a good remark, however we may want to understand why these tests started to fail with this PR specifically.

**Comment by Didayolo** [comment]
Maybe the problem is occurs because https://chahub.org/? does get the number of participants of the competitions? The renaming of `participants_count` may lead to a bug.

**Comment by ihsaan-ullah** [comment]
> Maybe the problem is occurs because https://chahub.org/ does get the number of participants of the competitions? The renaming of `participants_count` may lead to a bug.

The problem is in sending submissions to chahub but in the test there is a dummy chahub (no real URL is used) so that should not be a problem

**Comment by ihsaan-ullah** [comment]
The tests are failing because of these lines of code added in the Submission modal's save function

```python
if is_new:
            # Increment the submissions_count for the competition
            self.phase.competition.submissions_count += 1
            self.phase.competition.save()
```

Removing this code fixes the problem. The real issue here is the test itself. If we don't have any chahub then why do we have tests for it and why do we have chahub fields in the submission?

I think we should do the following:

- remove the tests (in this PR)
- remove any mention of chahub from the whole project (in a new PR as part of project cleaning)

**Comment by ihsaan-ullah** [comment]
Added tests for submisisons count and participants count

**Comment by Didayolo** [comment]
@ihsaan-ullah 

> remove the tests (in this PR)

OK for removing the test. Do you have a way to disable them, or do you want to simply erase them?

**Comment by ihsaan-ullah** [comment]
> OK for removing the test. Do you have a way to disable them, or do you want to simply erase them?

I can comment them for now instead of removing them. And later on remove them permanently in another PR

**Comment by ihsaan-ullah** [comment]
> 
> OK for removing the test. Do you have a way to disable them, or do you want to simply erase them?

For now I have commented the problematic tests. I am going to prepare a script to update all the competitions and then we can merge this PR

**Comment by ihsaan-ullah** [comment]
@Didayolo 

### Update counts for all competitions

Bash into django console
```
docker compose exec django ./manage.py shell_plus
```

Import and call the function
```python
from competitions.submission_participant_counts import compute_submissions_p
articipants_counts
compute_submissions_participants_counts()
```

**Pull request merged**
