### PR TITLE
Updates Sept 15-22 2024

### PR DESCRIPTION
**Pull request by bbearce**
# @ mention of reviewers

# A brief description of the purpose of the changes contained in this PR.
Attempting to catalog changes by week.

# Issues this PR resolves
Including the following bumps:
* [dependabot - Bump pillow from 8.0.1 to 10.3.0](https://github.com/codalab/codabench/pull/1493) - can close
* [dependabot - Bump jinja2 from 3.1.3 to 3.1.4](https://github.com/codalab/codabench/pull/1494) - can close
* [dependabot - Bump gunicorn from 20.0.4 to 22.0.0](https://github.com/codalab/codabench/pull/1495) - can close
* [dependabot - Bump requests from 2.20.0 to 2.32.2]
  * I messed up and updated in django so technically this still needs to be done for the compute worker # (https://github.com/codalab/codabench/pull/1489)
* [dependabot - Bump django from 2.2.17 to 2.2.18 and to 3.2.25 (65 versions away) eventually but we need to go slow as the amount of cascading changes is huge. We need to slowly update django and things around it and we should eventually get here.] # (https://github.com/codalab/codabench/pull/1492)
* [Bump django from 2.2.17 to 2.2.18]
* [Bump django from 2.2.18 to 2.2.19]
* [Bump django from 2.2.19 to 2.2.20]
* [Bump django from 2.2.20 to 2.2.25]

> Django makes a larger jump from 2.2.28 - 3.0. I believe some other more core packages will be affected and so I think this is a good line in the sand to draw. We should merge this and then do a batch of updates just for the 2.2.28 -> 3.0 django upgrade.

# A checklist for hand testing
- [x] make sure you rebuild django

```bash
docker build -f Dockerfile -t codabench-django:latest ./
# docker build --no-cache -f Dockerfile -t codabench-django:latest ./
```
> /Version_Bumps.md has this and automatted testing at the bottom for convenience.

# Any relevant files for testing
[link]('#') to any relevant files (or drag and drop into github)

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [x] Code review by reviewer
- [x] Hand tested by reviewer
- [x] CircleCi tests are passing
- [x] Ready to merge

### CODE REVIEW

**Comment by Didayolo** [comment]
@bbearce 

The `Version_Bumps.md` file might not reflect the changes I just made (Python 3.9.20, and Django 2.2.28).

Also, can you tell more about this file? How will it be updated in the future?

**Comment by Didayolo** [comment]
```python
 => [site_worker 2/8] RUN apt-get update && apt-get install -y gcc build-  5.8s
 => [site_worker 3/8] RUN curl -sSL https://install.python-poetry.org |   23.2s
 => [flower 3/9] RUN curl -sSL https://install.python-poetry.org | pytho  24.1s
 => [site_worker 4/8] RUN poetry config virtualenvs.create false           1.1s
 => [flower 4/9] RUN poetry config virtualenvs.create false                1.3s
 => [site_worker 5/8] RUN poetry config virtualenvs.in-project false       1.1s
 => [site_worker 6/8] COPY pyproject.toml poetry.lock ./                   0.1s
 => [flower 5/9] RUN poetry config virtualenvs.in-project false            1.2s
 => ERROR [site_worker 7/8] RUN poetry install                             2.3s
 => [flower 6/9] RUN poetry init --no-interaction                          1.2s
 => CANCELED [flower 7/9] RUN poetry add redis=3.0.1                       0.5s
------
 > [site_worker 7/8] RUN poetry install:
1.285 Skipping virtualenv creation, as specified in config file.
1.499 Installing dependencies from lock file
2.147 
2.148 pyproject.toml changed significantly since poetry.lock was last generated. Run `poetry lock [--no-update]` to fix the lock file.
------
failed to solve: process "/bin/sh -c poetry install" did not complete successfully: exit code: 1

Exited with code exit status 17
```

**Comment by bbearce** [comment]
That file was more my notes and process. It might be useful for some so thought about leaving it, but upon second thought, it's clutter so i'll maintain my oen copy unless you all want something from it. This branch has the updated develop branch stuff as I saw you rebase it. Added a couple commits to get the tests to pass.

**Comment by Didayolo** [comment]
@bbearce So should we merge this PR?

**Comment by bbearce** [comment]
Yes please!

**Pull request merged**
