### PR TITLE
leaked users fixed

### LINKED ISSUE #885: leak users
Hi,

The Django REST framework leaks the list of users (with emails) through the "collaborators" selector of the HTML competition submission form (bottom of the page https://www.codabench.org/api/competitions/).

Screenshot from 2023-05-22 14-52-30

Edit: Seems it only works when logged in 🙌. The extraction is possible through the GUI "Add collaborator" auto completion feature, but giving out the list like that might not be desired.

### PR DESCRIPTION
**Pull request by ihsaan-ullah**
# @ mention of reviewers
@Didayolo 

# A brief description of the purpose of the changes contained in this PR.
Now user email will not be leaked in these apis:

1.  https://www.codabench.org/api/competitions/
Screenshot 2023-06-11 at 1 12 35 AM

now only username is shown in collaborators 

2. https://www.codabench.org/api/participants/
Screenshot 2023-06-11 at 1 12 53 AM

Now email is removed from the participants 

# Issues this PR resolves
#885 

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [x] Code review by reviewer
- [x] Hand tested by reviewer
- [x] CircleCi tests are passing
- [x] Ready to merge

### CODE REVIEW

**Comment by ihsaan-ullah** [comment]
This may break and needs more investigation
Screenshot 2023-06-11 at 1 27 39 AM

**Comment by ihsaan-ullah** [comment]
The change in Competition participant may break this:
Screenshot 2023-06-11 at 1 27 39 AM

It needs more investigation

**Comment by ihsaan-ullah** [comment]
Now codabench/api.participants will show participants without email and in competition->participants tab emails will be shown


API: no email
Screenshot 2023-06-11 at 12 53 32 PM

Participant tab: with email
Screenshot 2023-06-11 at 12 53 21 PM

Now the issue can be closed

**Comment by dtuantran** [comment]
I think we should remove also "id" and "status" of users. Exposing the least information to public is the general security rule.

**Comment by Didayolo** [comment]
I rebased the branch to have the CircleCI test fix.

**Comment by ihsaan-ullah** [comment]
@dtuantran 

This is working fine. It shows all partiicpants from competitions where you are owner or collaborator
Screenshot 2023-06-21 at 12 03 46 PM

Adding a participant from this interface does not work because it needs a `user` object and we have hidden almost all the attributes
Screenshot 2023-06-21 at 12 17 16 PM


The issue solved in this PR is the data leakage i.e. email, status and id. If something else needs to be solved then a separate issue should be created about it

**Comment by dtuantran** [comment]
Tested, it's good to be merged !

**Comment by Didayolo** [comment]
> The change in Competition participant may break this:

You were right!

**Pull request merged**
