### PR TITLE
Server status - show/hide child submissions

### PR DESCRIPTION
**Pull request by ihsaan-ullah**
# @ mention of reviewers
@Didayolo 

# A brief description of the purpose of the changes contained in this PR.
Now in server status page there is an option to show child submissions. By default they are hidden

Default : show only parent (checkbox unchecked)
Screenshot 2023-08-21 at 3 47 08 PM

show parent and children (checkbox checked)
Screenshot 2023-08-21 at 3 47 17 PM

# Issues this PR resolves
- #744 -> Have a way to differentiate and show/hide the "secondary submissions", which are hidden submissions made when there are multiple tasks

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [ ] Code review by reviewer
- [ ] Hand tested by reviewer
- [x] CircleCi tests are passing
- [ ] Ready to merge

### CODE REVIEW

**Comment by Didayolo** [comment]
Remarks

- There is a typo "chilld" --> "child".

- We should add a question mark `(?)` next to "Show child submission" to give an explanation: child jobs are created when there are multiple tasks.

- There is a conflict to resolve with `views.py`. It is normal, it is because I have merged the other PR about this interface.

**Comment by ihsaan-ullah** [comment]
> * There is a conflict to resolve with `views.py`. It is normal, it is because I have merged the other PR about this interface.

Can you show me the conflict.

**Comment by ihsaan-ullah** [comment]
Question mark for explanation
Screenshot 2023-08-21 at 4 01 00 PM

with parent id when checked show child submissions
Screenshot 2023-08-21 at 4 01 39 PM

without parent id when no children are shown
Screenshot 2023-08-21 at 4 01 42 PM

**Comment by ihsaan-ullah** [comment]
Resolved the conflicts

**Pull request merged**
