### PR TITLE
Resource interface-> Task updates

### PR DESCRIPTION
**Pull request by ihsaan-ullah**
# @ mention of reviewers
@Didayolo 

# A brief description of the purpose of the changes contained in this PR.
In the resource interface, task table is updated to:
- Show task description in the table
- show task creator in the table
- make some space for description by removing `uploaded` column
- move shared with to task details
- move benchmarks to task details
- show shared with and used in competitions to owners only
- show in use in the table

# Screenshots

New task interface
Screenshot 2024-10-04 at 2 02 53 PM

Task detail shown to non-owners
Screenshot 2024-10-04 at 2 03 05 PM

Task detail shown to owners
Screenshot 2024-10-04 at 2 03 14 PM

# Issues this PR resolves
- #1589

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [x] Code review by reviewer
- [x] Hand tested by reviewer
- [x] CircleCi tests are passing
- [x] Ready to merge

### CODE REVIEW

**Comment by Didayolo** [comment]
Nice work.

> make some space for description by removing uploaded column

I think we should keep the information of when it was uploaded somewhere. Maybe in the details.

> move benchmarks to task details

Not sure this is a good idea. It is convenient to quickly check which benchmark the task is associated to, in order to recognize it quickly (especially when several tasks have the same name).

**Comment by ihsaan-ullah** [comment]
Task uploaded when added to task detail.
Screenshot 2024-10-08 at 11 07 26 AM

Showing competitions in the table will take most of the space because some competitions have long names. We should discuss this before adding it back to the table

**Comment by Didayolo** [comment]
@ihsaan-ullah 

Would it be possible that the whole row is clickable to show details, instead of just the title?

Capture d’écran 2024-10-11 à 13 17 42

This way it would be more intuitive and convenient.

**Comment by ihsaan-ullah** [comment]
Now details will be shown on Name and Description columns click. Click is not applied on other columns because they have some actions

**Pull request merged**
