### PR TITLE
Merge develop into master

### PR DESCRIPTION
**Pull request by Didayolo**
**TO BE TESTED**

Deployed on https://codabench-test.lri.fr/

### Cleanup and quota

- #918
- #958

At the bottom of the resources interface:

- [ ] Delete unused tasks
- [ ] Delete unused datasets
- [ ] Delete unused submissinos
- [ ] Delete failed submissions

### Phase status fixed
- #934

- [ ] Make a submission in a never ending phase
- [ ] Play around with phase dates and make submissions

### Dynamic news edition
- #952

- [ ] Add announcement and news
- [ ] Remove announcement and news
- [ ] Add documentation (in "administrator procedures"?) about this feature, with screenshots

### Number of entries in leaderboard fixed
- #966 

- [ ] add a submission to multi-tasked phase. without this fix it will show number of submissions x tasks in the leaderboard

### Leaked users fixed
- #929

### Organization

- #976 

- [ ] In the submission interface, the "Submit as..." scrolling bar should propose to create an organization if you don't have any.

- #959

- [ ] Try to add and delete an organization

### Add phase fixed

- #963

- [ ] Add a phase using the editor
- [ ] Try different dates, never ending, etc.
- [ ] Make a submission to the new phase
- [ ] Remove some phases

### Update text in front page

- #983

The paragraphs "What is CodaLab", "What is Codabench", "History of CodaLab", etc. was updated.

- [ ] Proof-read the paragraphs
- [ ] Test the links

### CODE REVIEW

**Comment by ihsaan-ullah** [comment]
My tests on https://codabench-test.lri.fr/

# Cleanup and quota
#918

### Correct cleanup statistic
- [x] number of unused submissions
- [x] number of unused tasks
- [x] number of unused datasets
- [x] number of failed submissions

### Delete
- [ ] Delete unused tasks
Deletion successful. the datasets used in that task (if not used in any other tasks) are not shown in the cleanup statistics - Solution: refresh unused tasks and unused datasets after task deletion
- [x] Delete unused datasets
- [x] Delete unused submissinos
- [ ] Delete failed submissions
Submission is deleted from competition but it stays in the resource->submissions tab
### Phase status fixed
#934

- [ ] Make a submission in a never ending phase
- [ ] Play around with phase dates and make submissions

**Comment by dtuantran** [comment]
After deleting unused task, I got the button "Delete unused dataset/program" but there is no dataset/program appeared on my account.
image

**Comment by ihsaan-ullah** [comment]
> After deleting unused task, I got the button "Delete unused dataset/program" but there is no dataset/program appeared on my account. 

This is because these datasets are auto created and if you check the auto created checkbox, you can see them

**Comment by dtuantran** [comment]
> > After deleting unused task, I got the button "Delete unused dataset/program" but there is no dataset/program appeared on my account.
> 
> This is because these datasets are auto created and if you check the auto created checkbox, you can see them

I clicked "autocreated" but there is nothing from my account

**Comment by Didayolo** [comment]
It's merged! 🎉

**Pull request merged**
