### PR TITLE
Competition - reward, contact_email, report

### PR DESCRIPTION
**Pull request by ihsaan-ullah**
# @ mention of reviewers
@Didayolo 

# A brief description of the purpose of the changes contained in this PR.
Now users can add the following to their competition

1. contact email
2. reward text 
3. report link 

# What is done in this PR

- [x] Add/Update contact email
- [x] Add/Update reward text 
- [x] Add/Update report link
- [x] Add these in competition creation and updation
- [x] Add `contact_email` and `reward` in yaml
- [x] update v2 unpacker to unpack `contact_email` and `reward`
- [x] show `contact_email` in forum
- [x] Show reward in competition list card

# Screenshots
When `contact email`,`reward`, and `report` are not added
Screenshot 2023-06-25 at 1 37 28 AM

When all of these are added
Screenshot 2023-06-25 at 1 37 46 AM

These can be added in the editor
Screenshot 2023-06-25 at 1 37 58 AM

YAML file can have `contact_email` and `reward` as shown below 
Screenshot 2023-06-25 at 1 51 02 AM

Competition unpacked using V2 unpacker using the above YAML
Screenshot 2023-06-25 at 1 54 10 AM

Contact email in forum
Screenshot 2023-06-25 at 2 23 20 AM

Competition list shows `reward` icon when competition has reward
Screenshot 2023-06-25 at 2 40 28 AM
Screenshot 2023-06-25 at 2 40 19 AM

# Issues this PR resolves

- #764 -> Editor / YAML fields -> Point 2,3,4

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [x] Code review by reviewer
- [x] Hand tested by reviewer
- [x] CircleCi tests are passing
- [x] Ready to merge

### CODE REVIEW

**Comment by ihsaan-ullah** [comment]
@Didayolo can you please check this PR locally. It works locally with me and the tests are also passing locally.

Branch: 
Screenshot 2023-08-06 at 12 56 35 PM

Tests:
Screenshot 2023-08-06 at 12 58 06 PM
Screenshot 2023-08-06 at 12 58 18 PM

**Comment by Didayolo** [comment]
@ihsaan-ullah : So we still have a problem with CircleCI everytime you create this `reward` field?

On a side note, the style should be improved (the emails are not using the right blue color, also `Competition report` should use the same blue as `Docker image`).

**Comment by ihsaan-ullah** [comment]
Screenshot 2023-08-09 at 4 11 34 PM

Report url style changed, copy button added

email style is already like docker image

**Comment by Didayolo** [comment]
And what about this page? Here `Start a new one` is using the blue used for clickable links in Codabench

Capture d’écran 2023-08-09 à 13 18 44

**Comment by ihsaan-ullah** [comment]
Screenshot 2023-08-09 at 4 37 29 PM
Forum contact email color changed

**Comment by Didayolo** [comment]
Good job. Now we really need to investigate together this problem of auto-tests.

**Comment by ihsaan-ullah** [comment]
> Good job. Now we really need to investigate together this problem of auto-tests.

Discussed this with Tuan. The functionality and tests both work with me locally. If we can verify that everything works locally with you and Tuan, then we can be sure that the problem could come from circle ci tests.

**Comment by dtuantran** [comment]
I've the same error when trying locally
image

**Comment by ihsaan-ullah** [comment]
doc updated: https://github.com/codalab/codabench/wiki/Yaml-Structure

**Pull request merged**
